Navbar fixed
OWASP/threat-dragon pull request #836
Opened 2024-01-12 18:01 UTC by SharanRP

**Summary**:
Fixed the navbar for mobile screens

**Description for the changelog**:
Changes made in the toggle button 

**Other info**:
closes "#835"

2024-01-14 09:32 UTC, jgadsden commented on example.env
> +ENCRYPTION_JWT_SIGNING_KEY=0c43457e9106e54da10f17f6d3bf9def
we require that real keys are not used here, as this is only an example file

2024-01-14 10:32 UTC, jgadsden requested changes

2024-01-14 10:32 UTC, jgadsden commented on td.vue/src/components/Navbar.vue
This is the real change, if I understand correctly, so if the other files could be reverted back to their unmodified state that would be great

2024-01-16 19:11 UTC, SharanRP commented
@jgadsden I have made the required changes

2024-01-16 21:27 UTC, jgadsden approved these changes
good to have this, thanks @SharanRP and will go ahead and merge

2024-01-16 21:36 UTC, merged