Prompt user to save model before quitting the app
OWASP/threat-dragon pull request #852
Opened 2024-02-04 16:03 UTC by raghav1030

**Summary**:

Prompts the user to save the model before quitting. Solves #846 

**Description for the changelog**:

Controlled the way Electron was closing the app previously. However, the guard on the route to #/dashboard has not been implemented yet. We can address this in a separate issue to better organize the code.

2024-02-04 18:19 UTC, jgadsden commented
Hello @raghav1030 , there might be a better way of handling the application close event
In a way this is similar to the Close Model menu action - we want to close the model so we request the renderer to do this, then the renderer notifies electron that it is safe to do so
So I think we should use the existing requests already in place, which allows for a consistent 'save changes?' dialog, and then allow the renderer to notify electron when it is safe to close the application

2024-02-04 19:07 UTC, raghav1030 commented
> Hello @raghav1030 , there might be a better way of handling the application close event In a way this is similar to the Close Model menu action - we want to close the model so we request the renderer to do this, then the renderer notifies electron that it is safe to do so So I think we should use the existing requests already in place, which allows for a consistent 'save changes?' dialog, and then allow the renderer to notify electron when it is safe to close the application

Hey @jgadsden, could you please verify if you're referring to this exact same behavior?

https://github.com/OWASP/threat-dragon/assets/94848646/1eb42e44-c707-4f22-beee-610578fdf0b9

2024-02-05 13:51 UTC, jgadsden requested changes
I think we should use the existing IPC between electron and the renderer
This allows the renderer to be the authority on whether to exit the application or not, and also allows reuse of the existing renderer dialog 
@raghav1030 could you consider this PoC :

```
diff --git a/td.vue/public/preload.js b/td.vue/public/preload.js
index 6300f36b..f0454e18 100644
--- a/td.vue/public/preload.js
+++ b/td.vue/public/preload.js
@@ -8,2 +8,3 @@ contextBridge.exposeInMainWorld('electronAPI', {
     // renderer to electron main
+    appClose: () => ipcRenderer.send('close-app'),
     updateMenu: (locale) => ipcRenderer.send('update-menu', locale),
@@ -17,2 +18,3 @@ contextBridge.exposeInMainWorld('electronAPI', {
     // electron main to renderer
+    onCloseAppRequest: (callback) => ipcRenderer.on('close-app-request', callback),
     onCloseModelRequest: (callback) => ipcRenderer.on('close-model-request', callback),
diff --git a/td.vue/src/desktop/desktop.js b/td.vue/src/desktop/desktop.js
index 061199a6..ec34dfef 100644
--- a/td.vue/src/desktop/desktop.js
+++ b/td.vue/src/desktop/desktop.js
@@ -22,2 +22,4 @@ protocol.registerSchemesAsPrivileged([
 let loadingScreen;
+let runApp = true;
+
 async function createWindow () {
@@ -58,2 +60,9 @@ async function createWindow () {
 
+    mainWindow.on("close" , (event) => {
+        if (runApp) {
+            event.preventDefault();
+            mainWindow.webContents.send('close-app-request');
+        }
+    });
+
     if (electronURL) {
@@ -110,2 +119,3 @@ app.on('ready', async () => {
 
+    ipcMain.on('close-app', handleCloseApp);
     ipcMain.on('update-menu', handleUpdateMenu);
@@ -132,2 +142,8 @@ app.on('open-file', function(event, path) {
 
+function handleCloseApp (_event) {
+    logger.log.debug('Close application request from renderer ');
+    runApp = false;
+    app.quit();
+}
+
 function handleUpdateMenu (_event, locale) {
diff --git a/td.vue/src/main.desktop.js b/td.vue/src/main.desktop.js
index b3612a24..ddb4e3d8 100644
--- a/td.vue/src/main.desktop.js
+++ b/td.vue/src/main.desktop.js
@@ -31,2 +31,12 @@ const getConfirmModal = () => {
 
+// request from electron to renderer to close the application
+window.electronAPI.onCloseAppRequest(async (_event) =>  {
+    console.debug('Close application request');
+    if (!app.$store.getters.modelChanged || await getConfirmModal()) {
+        console.debug('Closing application');
+        // send request back to electron server to close the application
+        window.electronAPI.appClose();
+    };
+});
+
 // request from electron to renderer to close the model
```

2024-02-06 08:46 UTC, jgadsden approved these changes
thanks @raghav1030 , going ahead with merge

2024-02-06 08:46 UTC, merged