ci: fix docker SBOM gathering
OWASP/threat-dragon pull request #966
Opened 2024-05-23 09:20 UTC by jkowalleck

**Summary**:

something with the docker SBOM gathering failed. see https://github.com/OWASP/threat-dragon/actions/runs/9203973802/job/25316590644#step:8:1
here is a possible fix.

**Description for the changelog**:

fix CI pipeline for docker SBOM.

**Other info**:
followup of #964

Thanks for submitting a pull request!
Please make sure you follow our code_of_conduct.md and our contributing guidelines contributing.md

2024-05-31 15:08 UTC, jkowalleck commented
@jgadsden, I think this is a needed fix

2024-05-31 15:23 UTC, jgadsden commented
apologies for the delay @jkowalleck , I have been traveling and not been able to review it; but I hope to get to it sometime this weekend

2024-06-02 12:54 UTC, jgadsden requested changes
the changes look good, but could you make a change in all three files?
after looking at the pipelines afresh, the 'SBOM combiner' step does not need to rely on  'server_unit_tests' step because 'build_docker_image' already relies on 'server_unit_tests' step, so could the new 'server_unit_tests' dependency be removed from the 'SBOM combiner' step in all three files?

2024-06-02 16:17 UTC, jkowalleck commented
> the changes look good, but could you make a change in all three files? after looking at the pipelines afresh, the 'SBOM combiner' step does not need to rely on 'server_unit_tests' step because 'build_docker_image' already relies on 'server_unit_tests' step, so could the new 'server_unit_tests' dependency be removed from the 'SBOM combiner' step in all three files?

I would leave it as is. All the `needs` are listed for a reason: they produce `SBOM-*` artifacts, that need to be combined.

2024-06-02 17:45 UTC, jgadsden approved these changes
Yes, that is a good point @jkowalleck so please go ahead and merge in the changes

2024-06-02 19:48 UTC, jkowalleck commented
re https://github.com/OWASP/threat-dragon/pull/966#pullrequestreview-2092570636

sorry, i cannot, i dont have permissions.

2024-06-02 20:48 UTC, merged